**ALGORITMO GENÉTICO**       

La **función a minimizar** es: f = (x1^2 + x2 -11)^2 + (x1 + x2^2 -7)^2;

**Rango de valores:** 0<=x1,x2<=6;
**Número de individuos iniciales:** 20;
**Resolución =** 0.006;


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
xu = 6;             #Límite inferior
xl = 0;             #Límite superior
res = 0.006;        #Resolución
tamanoPobla = 20;   #Tamaño de la Población
#Ambas variables tienen el mismo límite. 

In [3]:
# Calcular el número de bits (q) a utilizar para representar cada variable, con una resolución de 0.006 en el intervalo (0,6):

q = np.ceil(np.log2(((xu - xl)/(res))+1))


In [4]:
def randPopulationPlantilla(xu,xl,tamanoPobla,q):
  #binPop: población de números binarios
  #decodedV: números binarios en decimal
  #r: valores en decimal de las variables x1 y x2;

  decodedV = np.random.randint(0,(2**q)-1, size=(tamanoPobla,1)) #Se crea una matriz de valores enteros aleatorios entre 0 y (2^q)-1

  binPop = np.zeros((tamanoPobla,int(q)))
  cont = 0

  #Ciclo para crear matriz de valores binarios
  for i in range(decodedV.shape[0]): 
    binValue = format(decodedV[i,0], '#012b').replace("0b", "")
    temp = list(map(int, [*binValue]))
    binPop[cont,:] = temp
    cont+=1

  #Valores en decimal de las variables x1 y x2
  r = ((xu-xl)/((2**q)-1))*decodedV


  return(binPop,decodedV,r)



In [5]:
#Inicialización de la Población de Individuos
binPopx1,decodedVx1,rx1 = randPopulationPlantilla(xu,xl,tamanoPobla,q)
binPopx2,decodedVx2,rx2 = randPopulationPlantilla(xu,xl,tamanoPobla,q)

In [6]:
#Desde aquí empezamos a realizar los pasos que dicen completar e implementar los pasos mencionados.
print(q)
print(binPopx2)


10.0
[[1. 0. 0. 1. 0. 1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [1. 1. 0. 1. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 1. 0. 1. 1. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 0. 1. 1. 0. 1. 1. 0.]
 [1. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0. 1. 1. 1. 0. 1.]
 [0. 1. 0. 1. 1. 1. 0. 1. 0. 1.]
 [1. 1. 0. 1. 1. 0. 1. 1. 0. 0.]]


In [7]:
#Cálculo de la Función Fitness
# formula: f = (x1^2 + x2 -11)^2 + (x1 + x2^2 -7)^2;

def Fitness(rx1,rx2):
  f = np.zeros((20,1))
  #Completar
  for i in range(20):
    cal = (((rx1[i]**2) + rx2[i] -11)**2) + ((rx1[i] + (rx2[i])**2 - 7)**2)
    f[i] = cal
  Fit = 1/(f+1)

  print(Fit)

  return (Fit,f)



In [8]:
Fit, f2 = Fitness(rx1,rx2)

[[0.00127552]
 [0.00236407]
 [0.00119383]
 [0.02687462]
 [0.00284174]
 [0.01213853]
 [0.07661111]
 [0.01636194]
 [0.00729506]
 [0.01414621]
 [0.00133366]
 [0.00889024]
 [0.01327628]
 [0.09829161]
 [0.08061519]
 [0.01436162]
 [0.01048417]
 [0.01776675]
 [0.00200882]
 [0.00137949]]


In [9]:
#Cálculo de la Reproducción
def Reproduccion(Fit,binPopx1,binPopx2):
  P = np.zeros((20,1))
  PA = np.zeros((20,1))
  MP = np.zeros((20,2))
  MR = np.zeros((20, int(q*2)))
  m = Fit.shape
  #Completar:
  
  MP[0,0] = 0.0
  
  for s in range(m[0]):
    K = np.random.rand()
    #Probabilidades:
    for i in range(m[0]):
      P[i] = Fit[i] / np.sum(Fit)

    #Probabilidad Acumulada
    for j in range(m[0] - 1): 
      PA[0, 0] = P[0, 0]
      PA[(j + 1), 0] = PA[j, 0] + P[(j + 1), 0]

    #Matriz Probabilidades
    for l in range(m[0] - 1):
      MP[0, 1] = PA[0, 0]
      MP[(l + 1), 0] = PA[l , 0]
      MP[(l + 1), 1] = PA[(l + 1), 0]

    #Cálculo de fila 
    for k in range(m[0]):
      if K >= MP[k, 0] and K <= MP[(k + 1), 0]:
        fila = k
    #Metodo Ruleta
    MR[s, :] = np.concatenate((binPopx1[(int(fila)),:], binPopx2[(int(fila)),:]), axis=0)

  
  return (MP, PA, P, K, fila, MR)

In [10]:
MP, PA, P, K, fila, MR = Reproduccion(Fit,binPopx1,binPopx2)
print(MR)


[[0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1.

In [84]:
#Cálculo de Crossover
def Crossover(MR):
   MC = MR
   m = MR.shape
   m60 = int((m[0] * 0.60))

   #Completar:
   for i in range(0, m60, 2):
      K = np.random.randint(0, m[0])

      Padre1 = MC[i, :]
      Padre2 = MC[(i + 1), :]

      Hijo1 = Padre1[:K]
      Hijo11 = Padre2[K:]

      Hijo2 = Padre2[:K]
      Hijo22 = Padre1[K:]

      X1 = np.concatenate((Hijo1, Hijo11), axis=0)
      X2 = np.concatenate((Hijo2, Hijo22), axis=0)

      MC[i,:] = X1
      MC[(i + 1),:] = X2  
   return (MC, K, Padre1, Padre2, X1)

In [95]:
MC, K, Padre1, Padre2, X1 = Crossover(MR)
print(K)
print(MC)



7
[[0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 

In [ ]:
#Cálculo de la Mutación
def Mutacion(MC):
  
  #Completar:

  MM = 0


  return (MM)

In [ ]:
#Paso Intermedio

def MM2IntmdVal(MM):
  binPopx1 = MM[:,0:int(q)]
  binPopx2 = MM[:,int(q):]


  for i in range(tamanoPobla):
    binValX1 = binPopx1[i,:].astype(int)
    binValX2 = binPopx2[i,:].astype(int)

    binValX1Str = (np.array_str(binValX1)).replace(' ','')[1:-1]
    binValX2Str = (np.array_str(binValX2)).replace(' ','')[1:-1]

    decodX1 = int(binValX1Str,2)
    decodX2 = int(binValX2Str,2)

    rx1[i,0] = ((xu-xl)/((2**q)-1))*decodX1
    rx2[i,0] = ((xu-xl)/((2**q)-1))*decodX2

  return(binPopx1,binPopx2,rx1,rx2)


In [ ]:
#Definicion Parámetro Iniciales del problema:

xu = 6;             #Límite inferior
xl = 0;             #Límite superior
res = 0.006;        #Resolución
tamanoPobla = 20;   #Tamaño de la Población

NumIteraciones = 100
f_history = np.zeros((NumIteraciones,1))

# Calcule el número de bits (q) a utilizar para representar cada variable, con una resolución de 0.006 en el intervalo (0,6):
q = np.ceil(np.log2(((xu - xl)/(res))+1))


#Inicialización de la Población de Individuos
binPopx1,decodedVx1,rx1 = randPopulationPlantilla(xu,xl,tamanoPobla,q)
binPopx2,decodedVx2,rx2 = randPopulationPlantilla(xu,xl,tamanoPobla,q)

for l in range(NumIteraciones):
  Fit,f = Fitness(rx1,rx2)
  f_history[l,0] = min(f)
  MR = Reproduccion(Fit,binPopx1,binPopx2)
  MC = Crossover(MR)
  MM = Mutacion(MC)
  (binPopx1,binPopx2,rx1,rx2) = MM2IntmdVal(MM)

Fit,f = Fitness(rx1,rx2)
posMin = np.argmin(f)
print("El valor de x1 que minimiza la función es: ", rx1[int(posMin)])
print("El valor de x2 que minimiza la función es: ", rx2[int(posMin)])
plt.plot(f_history)